var compo = compo || {};
compo = {
		
	search_result :()=>{
		return '<div class="lookup-cont faq-cont tab-cont">'
		+'<ul class="list-view faq-list" id="airOfferList">'
		+'	<li>'
		+'		<div class="list-head question table-st" fareindex="33">'
		+'			<div class="cell-left flight-name">'
		+'				<span class="air-logo">'
		+'					<img src="/resource_pc/images/logo/VJ.png" airlogo="1">'
		+'				</span>'
		+'				<span class="air-info">'
		+'					<span class="air-name ">비엣젯항공   </span>'
							+''
		+'					<span class="air-num" style="max-width: 200px;">VJ0963</span>'
		+'				</span>'
		+'			</div>'
		+'			<div class="cell-center flight-time">'
		+'				<div class="time-box depart">'
		+'					<span class="code">ICN</span>'
		+'					<span class="time">06:25</span>'
		+'				</div>'
		+'				<div class="time-box flight-img">'
		+'					<span class="total-time">&nbsp;</span>'
							+''
		+'					<span class="air-img"></span>'
		+'					<div class="air-info-box">'
							+''
		+'					</div>'
		+'				</div>'
		+'				<div class="time-box arrive">'
		+'					<span class="code">HAN</span>'
		+'					<span class="time">08:55</span>'
		+'				</div>'
		+'			</div>'
		+'			<div class="cell-center" style="color:#999;font-size:12px;width:13%;text-align:left;">4시간 30분 소요'
		+'				<br>'
		+'				<a href="javascript:void(0)" onclick="moveBaggagePage(event,&quot;https://bit.ly/2KqLVLY&quot;)" class="btn-text" style="font-size:12px;">수하물 규정 확인</a>'
		+'			</div>'
		+'			<div class="cell-right trip-price">'
		+'				<div>'
		+'					<span class="blue">224,100</span>원'
		+'					<div class="price-info-box" style="display: block; opacity: 0; cursor: default;">'
		+'						<div class="total-price-info">'
		+'							<dl class="table-st">'
		+'								<dt>'
		+'									<span class="cell-left">성인 항공권</span>'
		+'									<span class="cell-right">224,100<span class="unit">원</span></span>'
		+'									<span class="cell-right">X 1</span>'
		+'								</dt>'
		+'								<dd>'
		+'									<span class="cell-left">항공권료</span>'
		+'									<span class="cell-right">98,000원</span>'
		+'									<span class="cell-right"></span>'
		+'								</dd>'
		+'								<dd>'
		+'									<span class="cell-left">유류할증료</span>'
		+'									<span class="cell-right">57,200원</span>'
		+'									<span class="cell-right"></span>'
		+'								</dd>'
		+'								<dd>'
		+'									<span class="cell-left">제세공과금</span>'
		+'									<span class="cell-right">58,900원</span>'
		+'									<span class="cell-right"></span>'
		+'								</dd>'
		+'								<dd>'
		+'									<span class="cell-left">발권대행료</span>'
		+'									<span class="cell-right">10,000원</span>'
		+'									<span class="cell-right"></span>'
		+'								</dd>'
		+'							</dl>'
		+'						</div>'
		+'						<div class="table-st total-price-sum">'
		+'							<div class="cell-left">총 요금</div>'
		+'							<div class="cell-right trip-price">'
		+'								<span class="blue">224,100</span>'
		+'								<span>원</span>'
		+'							</div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'			</div>'
		+'			<div class="cell-right expand-icon">'
		+'				<i class="xi-angle-down-min"></i>'
		+'				<i class="xi-angle-up-min"></i>'
		+'			</div>'
		+'		</div>'
		+'	</li>'
		+'</ul>'
		+'</div>'

	}
	
}